--======================================
-- Borrado de las tablas de AspNet
--======================================

DROP TABLE [dbo].[aspnet_WebEvent_Events]
DROP TABLE [dbo].[aspnet_UsersInRoles]
DROP TABLE [dbo].[aspnet_Roles]
DROP TABLE [dbo].[aspnet_Profile]
DROP TABLE [dbo].[aspnet_PersonalizationPerUser]
DROP TABLE [dbo].[aspnet_PersonalizationAllUsers]
DROP TABLE [dbo].[aspnet_Paths]
DROP TABLE [dbo].[aspnet_Membership]
DROP TABLE [dbo].[aspnet_Users]
DROP TABLE [dbo].[aspnet_Applications]
DROP TABLE [dbo].[aspnet_SchemaVersions]

--=================================================
-- Borrado de Procedimientos Almacenados de AspNet
--=================================================
DROP PROCEDURE [dbo].[aspnet_AnyDataInTables]
DROP PROCEDURE [dbo].[aspnet_Applications_CreateApplication]
DROP PROCEDURE [dbo].[aspnet_Membership_ChangePasswordQuestionAndAnswer]
DROP PROCEDURE [dbo].[aspnet_Membership_CreateUser]
DROP PROCEDURE [dbo].[aspnet_Membership_FindUsersByEmail]
DROP PROCEDURE [dbo].[aspnet_Membership_FindUsersByName]
DROP PROCEDURE [dbo].[aspnet_Membership_GetAllUsers]
DROP PROCEDURE [dbo].[aspnet_Membership_GetNumberOfUsersOnline]
DROP PROCEDURE [dbo].[aspnet_Membership_GetPassword]
DROP PROCEDURE [dbo].[aspnet_Membership_GetPasswordWithFormat]
DROP PROCEDURE [dbo].[aspnet_Membership_GetUserByEmail]
DROP PROCEDURE [dbo].[aspnet_Membership_GetUserByName]
DROP PROCEDURE [dbo].[aspnet_Membership_GetUserByUserId]
DROP PROCEDURE [dbo].[aspnet_Membership_ResetPassword]
DROP PROCEDURE [dbo].[aspnet_Membership_SetPassword]
DROP PROCEDURE [dbo].[aspnet_Membership_UnlockUser]
DROP PROCEDURE [dbo].[aspnet_Membership_UpdateUser]
DROP PROCEDURE [dbo].[aspnet_Membership_UpdateUserInfo]
DROP PROCEDURE [dbo].[aspnet_Paths_CreatePath]
DROP PROCEDURE [dbo].[aspnet_Personalization_GetApplicationId]
DROP PROCEDURE [dbo].[aspnet_PersonalizationAdministration_DeleteAllState]
DROP PROCEDURE [dbo].[aspnet_PersonalizationAdministration_FindState]
DROP PROCEDURE [dbo].[aspnet_PersonalizationAdministration_GetCountOfState]
DROP PROCEDURE [dbo].[aspnet_PersonalizationAdministration_ResetSharedState]
DROP PROCEDURE [dbo].[aspnet_PersonalizationAdministration_ResetUserState]
DROP PROCEDURE [dbo].[aspnet_PersonalizationAllUsers_GetPageSettings]
DROP PROCEDURE [dbo].[aspnet_PersonalizationAllUsers_ResetPageSettings]
DROP PROCEDURE [dbo].[aspnet_PersonalizationAllUsers_SetPageSettings]
DROP PROCEDURE [dbo].[aspnet_PersonalizationPerUser_GetPageSettings]
DROP PROCEDURE [dbo].[aspnet_PersonalizationPerUser_ResetPageSettings]
DROP PROCEDURE [dbo].[aspnet_PersonalizationPerUser_SetPageSettings]
DROP PROCEDURE [dbo].[aspnet_Profile_DeleteInactiveProfiles]
DROP PROCEDURE [dbo].[aspnet_Profile_DeleteProfiles]
DROP PROCEDURE [dbo].[aspnet_Profile_GetNumberOfInactiveProfiles]
DROP PROCEDURE [dbo].[aspnet_Profile_GetProfiles]
DROP PROCEDURE [dbo].[aspnet_Profile_GetProperties]
DROP PROCEDURE [dbo].[aspnet_Profile_SetProperties]
DROP PROCEDURE [dbo].[aspnet_RegisterSchemaVersion]
DROP PROCEDURE [dbo].[aspnet_Roles_CreateRole]
DROP PROCEDURE [dbo].[aspnet_Roles_DeleteRole]
DROP PROCEDURE [dbo].[aspnet_Roles_GetAllRoles]
DROP PROCEDURE [dbo].[aspnet_Roles_RoleExists]
DROP PROCEDURE [dbo].[aspnet_Setup_RemoveAllRoleMembers]
DROP PROCEDURE [dbo].[aspnet_Setup_RestorePermissions]
DROP PROCEDURE [dbo].[aspnet_Users_CreateUser]
DROP PROCEDURE [dbo].[aspnet_Users_DeleteUser]
DROP PROCEDURE [dbo].[aspnet_UsersInRoles_AddUsersToRoles]
DROP PROCEDURE [dbo].[aspnet_UsersInRoles_FindUsersInRole]
DROP PROCEDURE [dbo].[aspnet_UsersInRoles_GetRolesForUser]
DROP PROCEDURE [dbo].[aspnet_UsersInRoles_GetUsersInRoles]
DROP PROCEDURE [dbo].[aspnet_UsersInRoles_IsUserInRole]
DROP PROCEDURE [dbo].[aspnet_UsersInRoles_RemoveUsersFromRoles]
DROP PROCEDURE [dbo].[aspnet_WebEvent_LogEvent]
DROP PROCEDURE [dbo].[aspnet_UnRegisterSchemaVersion]
DROP PROCEDURE [dbo].[aspnet_CheckSchemaVersion]

GO
		