//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mininterior.RusicstMVC.Aplicacion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mininterior.RusicstMVC.Aplicacion.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos ingresados no coinciden. Por favor revise.
        /// </summary>
        public static string ClaveErrada {
            get {
                return ResourceManager.GetString("ClaveErrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario con éste Correo Electrónico. Por favor revise..
        /// </summary>
        public static string EmailRepetido {
            get {
                return ResourceManager.GetString("EmailRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ya realizó la validación correspondiente. Esté atento a la respuesta de su solicitud..
        /// </summary>
        public static string MsjTokenValidado {
            get {
                return ResourceManager.GetString("MsjTokenValidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no es posible borrarlo porque se encuentra relacionado en otro proceso. Por favor revise..
        /// </summary>
        public static string NoSePuedeBorrar {
            get {
                return ResourceManager.GetString("NoSePuedeBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazo de Solicitud de Usuario.
        /// </summary>
        public static string RechazoSolicitud {
            get {
                return ResourceManager.GetString("RechazoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperación de Contraseña.
        /// </summary>
        public static string RecuperarClave {
            get {
                return ResourceManager.GetString("RecuperarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobación de Usuario.
        /// </summary>
        public static string SolicitudAprobacion {
            get {
                return ResourceManager.GetString("SolicitudAprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de Solicitud.
        /// </summary>
        public static string SolicitudConfirmacion {
            get {
                return ResourceManager.GetString("SolicitudConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido una excepción al intentar crear la solicitud de usuario..
        /// </summary>
        public static string SolicitudCreacionError {
            get {
                return ResourceManager.GetString("SolicitudCreacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Usuario.
        /// </summary>
        public static string SolicitudUsuario {
            get {
                return ResourceManager.GetString("SolicitudUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario ó el Correo Electrónico digitados no coinciden. Por favor revise..
        /// </summary>
        public static string UsuarioYCorreoDiferentes {
            get {
                return ResourceManager.GetString("UsuarioYCorreoDiferentes", resourceCulture);
            }
        }
    }
}
