//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mininterior.RusicstMVC.Aplicacion.Mensajeria {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajesCorreo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesCorreo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mininterior.RusicstMVC.Aplicacion.Mensajeria.MensajesCorreo", typeof(MensajesCorreo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creación o Actualización de  Usuario - PASO 3 DE 3.
        /// </summary>
        public static string AsuntoCreacionUsuario {
            get {
                return ResourceManager.GetString("AsuntoCreacionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazo de Solicitud de Usuario - PASO 3 DE 3.
        /// </summary>
        public static string AsuntoRechazoSolicitud {
            get {
                return ResourceManager.GetString("AsuntoRechazoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperación de Contraseña RUSICST.
        /// </summary>
        public static string AsuntoRecuperarClave {
            get {
                return ResourceManager.GetString("AsuntoRecuperarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptación de Solicitud de Usuario - PASO 2 DE 3.
        /// </summary>
        public static string AsuntoSolicitudUsuarioAceptacion {
            get {
                return ResourceManager.GetString("AsuntoSolicitudUsuarioAceptacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de Solicitud de Usuario - PASO 1 DE 3.
        /// </summary>
        public static string AsuntoSolicitudUsuarioConfirmacion {
            get {
                return ResourceManager.GetString("AsuntoSolicitudUsuarioConfirmacion", resourceCulture);
            }
        }
    }
}
